Update vendored S2 version (#257)
* Update vendored abseil-cpp (#258)

* copy some prior art

* remove previous absl files

* renove abseil files

* add vendor in tools/

* it works!

* fix some initial check issues

* lazier config

* remove r 3.6 on windows

* see if removing the braces helps

* maybe fix substitution

* just link it all

* try again

* helppers

* slight updates

* better flags

* more cmake

* just hard code it

* pkg-config

* add gnu make to makefile

* don't link rt

* ignore windows dir

* possible progress for R 4.2

* more win checks

* don't use configure.win

* maybe working on R 4.2

* also use cxx17

* check for absl

* maybe with quotes

* version and news

* maybe the right flags

* maybe try unifying makevars

* maybe work on R 4.2/4/1

* maybe fix makevars.win

* maybe fix for R 4.2

* maybe fix R 4.1

* see if we're getting the right if statement

* temp fix for old s2 warnings

* maybe fix again

* try again

* document configure.win

* maybe fix R 4.2 warning

* try again for globals

* maybe use different namespace

* use pkg-config abseil

* fix comment

* maybe fix

* quality of life improvements

* clean news

* better cleanup/configure

* reasonable path to not awful dev setup without system abseil

* enforce minimum version in pkg-config check

* start to update

* maybe it builds

* maybe fix vendored version

* maybe on windows

* fix define

* maybe fix snprintf warning

* use union instead of coverage union

* don't include testing utils

* add status in windows

* try the define trick

* fix cleanup

* maybe fix compilation on windows

* remove version-specific override

* try again to fix

* reapply coding hack

* maybe fix stderr references

* skip old R on windows for now

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -94,17 +94,54 @@ fi
 fi #SONAME
 fi #AUTOBREW
 
-# Define system endianness (compile-time endianness using system/compiler
-# defines isn't detected on Solaris)
-# based on endian detection from the feather package by @hadley
-R_ENDIAN=`${R_HOME}/bin/Rscript -e 'cat(.Platform$endian)'`
-# Trim off any warning messages that Rscript appends in front of the platform endianness
-R_ENDIAN=`expr "$R_ENDIAN" : '.*\(little\)$'`
-SYS_ENDIAN=""
-if [ "$R_ENDIAN" = "little" ]; then
-    PKG_CFLAGS="$PKG_CFLAGS -DIS_LITTLE_ENDIAN"
+# Check pkg-config for abseil-cpp, but fall back to a cmake build.
+# This should possibly be updated to check that the pkg-config detected
+# version will actually work; however, the version of abseil that included
+# pkg-config files is about the same as the minimum version required here.
+export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:`pwd`/tools/pkgconfig"
+
+# Allow developers to set R_S2_ABSL_HOME in .Renviron to avoid building
+# Abseil on every package rebuild. This can be built from this directory using
+# tools/build_absl.sh path/to/dir (then R_S2_ABSL_HOME=path/to/dir in .Renviron)
+if [ ! -z "${R_S2_ABSL_HOME}" ]; then
+  export PKG_CONFIG_PATH="{$R_S2_ABSL_HOME}/lib/pkgconfig:${PKG_CONFIG_PATH}"
+fi
+
+echo "** Using PKG_CONFIG_PATH=${PKG_CONFIG_PATH}"
+
+if pkg-config absl_s2 --libs 2>/dev/null; then
+  echo "** Using abseil-cpp from pkg-config"
+
+  PKGCONFIG_CFLAGS=`pkg-config --cflags-only-I absl_s2`
+  PKGCONFIG_LIBS=`pkg-config --libs absl_s2`
+  PKG_CFLAGS="${PKGCONFIG_CFLAGS} ${PKG_CFLAGS}"
+  PKG_LIBS="${PKGCONFIG_LIBS} ${PKG_LIBS}"
 else
-    PKG_CFLAGS="$PKG_CFLAGS -DIS_BIG_ENDIAN"
+  echo "** Building abseil-cpp using cmake"
+  CMAKE_INSTALL_PREFIX="`pwd`/tools/dist"
+  if tools/build_absl.sh "${CMAKE_INSTALL_PREFIX}"; then
+    echo "** Done!"
+  else
+    echo "** CMake build of Abseil failed"
+    echo "** Abseil can be installed with:"
+    echo "** - apt-get install libabsl-dev"
+    echo "** - dnf install abseil-cpp-devel"
+    echo "** - brew install abseil"
+    echo "** If a system install of Abseil is not possible, cmake is required to build"
+    echo "** the internal vendored copy."
+    exit 1
+  fi
+
+  # Clean up build directory
+  rm -rf tools/build
+
+  R_S2_ABSL_HOME="`pwd`/tools/dist"
+  export PKG_CONFIG_PATH="${R_S2_ABSL_HOME}/lib/pkgconfig:${PKG_CONFIG_PATH}"
+  echo "** Using PKG_CONFIG_PATH=${PKG_CONFIG_PATH}"
+  PKGCONFIG_LIBS=`pkg-config --libs absl_s2`
+
+  PKG_CFLAGS="-I${R_S2_ABSL_HOME}/include ${PKG_CFLAGS}"
+  PKG_LIBS="${PKGCONFIG_LIBS} ${PKG_LIBS}"
 fi
 
 # From apache/arrow/r/configure:
@@ -116,7 +153,6 @@ fi
 
 echo "Using PKG_LIBS=$PKG_LIBS"
 echo "Using PKG_CFLAGS=$PKG_CFLAGS"
-
 
 # Write to Makevars
 sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars
